- LeapSerial/optional.h
- src/leapserial/CMakeLists.txt
- src/leapserial/test/CMakeLists.txt
- src/leapserial/test/LeapArchiveTest.cpp
- src/leapserial/test/OptionalTest.cpp
The STL will someday have something like this in it, then we can remove this implementation.  In the meantime, however, we need to supply one of our own in order to be compatible with the Protobuf format without incurring a pretty big performance hit.
> Add an optional header concept and corresponding unit test.

- LeapSerial/Archive.h
- src/leapserial/Archive.cpp
Without this we can't detect EOF except to read until we fail, and this causes avoidable exceptions to be thrown.
> Archive type should provide an EOF accessor

- LeapSerial/field_serializer_t.h
- LeapSerial/serial_traits.h
Vector and map serializers are constructing temporary `field_serializer_t` items on the stack every time they are called for.  This practice is extremely inefficient and is one of the reasons that the `field_serializer_t::GetDescriptor()` method was provided to begin with.  Fix these routines so they call `GetDescriptor()` as the other serializers do.
> Fix extremely inefficient use of GetDescriptor

- LeapSerial/Archive.h
- LeapSerial/ArchiveFlatbuffer.h
- LeapSerial/ArchiveJSON.h
- LeapSerial/IArchiveImpl.h
- LeapSerial/IArray.h
- LeapSerial/IDictionary.h
- LeapSerial/OArchiveImpl.h
- LeapSerial/serial_traits.h
- src/leapserial/ArchiveFlatbuffer.cpp
- src/leapserial/ArchiveJSON.cpp
- src/leapserial/CMakeLists.txt
- src/leapserial/IArchiveImpl.cpp
- src/leapserial/OArchiveImpl.cpp
This interface type reduces the complexity and expense associated with calling the dictionary and vector serialization operations.  As we add more output formatters, simplicity in this interface will become increasingly important.
> Switch Array and Dictionary methods to use an explicit interface type

- .travis.yml
- LeapSerial/Archive.h
- LeapSerial/ArchiveProtobuf.h
- LeapSerial/IArchiveProtobuf.h
- LeapSerial/OArchiveProtobuf.h
- src/leapserial/CMakeLists.txt
- src/leapserial/IArchiveImpl.cpp
- src/leapserial/IArchiveProtobuf.cpp
- src/leapserial/OArchiveProtobuf.cpp
- src/leapserial/ProtobufUtil.cpp
- src/leapserial/ProtobufUtil.hpp
- src/leapserial/test/ArchiveProtobufTest.cpp
- src/leapserial/test/CMakeLists.txt
- src/leapserial/test/TestProtobuf.proto
This formatter will allow LeapSerial structures to target the protobuf wire format.  Protobuf wire-level compatibility makes it possible to interop with protobuf comms layers without needing to generate a .proto file.
This formatter is only meant to be an initial implementation, and will be tested but not to the extreme.  Subsequent pull requests should ensure the implementation is adequately tested for general use.
> Implement protobuf output formatter

- scripts/copyright_check.sh
- scripts/whitespace_check.sh
Looks like this still has paths that were valid in Autowiring but are not valid here, fix the linter script to reflect the current directory structure.
> Fix whitespace scripts

- LeapSerial/ArchiveProtobuf.h
- LeapSerial/IArchiveProtobuf.h
- src/leapserial/IArchiveProtobuf.cpp
Caused by an unbounded/torn dictionary read operation and an EOF check that was occuring way too late.
> Fix error uncovered during unit testing

- LeapSerial/serialization_error.h
- src/leapserial/CMakeLists.txt
- src/leapserial/IArchiveProtobuf.cpp
- src/leapserial/OArchiveProtobuf.cpp
- src/leapserial/ProtobufUtil.cpp
- src/leapserial/ProtobufUtil.hpp
- src/leapserial/serialization_error.cpp
Move `protobuf` to the internal namespace, create a separate `serialization_exception` base type to report all serialization-related exceptions.
> General namespace cleanup

- LeapSerial/IInputStream.h
- LeapSerial/IOutputStream.h
- src/leapserial/CMakeLists.txt
These types are interfaces, they should be defined in a minimum-dependency setting
> Split IInputStream and IOutputStream into their own headers

- src/leapserial/test/ArchiveProtobufTest.cpp
- src/leapserial/test/CMakeLists.txt
- src/leapserial/test/TestProtobufLS.hpp
Should be useful for other tests, put it in a common location.
> Move protobuf reference class to its own header

- LeapSerial/Descriptor.h
- src/leapserial/Descriptor.cpp
This allows users to provide string names for their datatypes for reflection purposes.  This might be replaced at a later date with an `autowiring::demangle` variant, but for now we'll encourage manual naming.
> Add name concept to LeapSerial descriptor

- LeapSerial/Archive.h
- LeapSerial/IInputStream.h
- LeapSerial/IOutputStream.h
Somehow managed to forget to move these definitions out of here and into the headers created in #21, fix that.
> Fix accidentally duplicated code

- LeapSerial/Descriptor.h
- LeapSerial/field_serializer.h
- LeapSerial/field_serializer_t.h
- LeapSerial/serial_traits.h
- src/leapserial/test/SerializationTest.cpp
This allows reflection to be done on these types, where formerly the whole serialization process was quite opaque.
> Add an interface concept for array, map, and object types

- LeapSerial/Descriptor.h
- LeapSerial/field_descriptor.h
We will likely need this often when we do schema formatting, add it.  Also make `descriptor::name` non-const so we can reassign it at runtime.
> Add an explicit overload to field_descriptor for synthetic types

- .travis.yml
- LeapSerial/LeapSerial.h
- LeapSerial/SchemaWriterProtobuf.h
- src/leapserial/CMakeLists.txt
- src/leapserial/ProtobufUtil.cpp
- src/leapserial/ProtobufUtil.hpp
- src/leapserial/SchemaWriterProtobuf.cpp
- src/leapserial/test/CMakeLists.txt
- src/leapserial/test/SchemaTest.cpp
- src/leapserial/test/TestProtobuf.proto
- src/leapserial/test/TestProtobufLS.hpp
This allows LeapSerial descriptors to be written out as a .proto file to make it possible to compile deserializers in other languages using Google protoc.
> Add protobuf schema writer and unit test

- leapserial-config.cmake.in
This changeup is required to allow leapserial to be referenced in a non-install build.
> Fix bad external CMake reference

- src/leapserial/test/CMakeLists.txt
This is required because these tests will not run correctly in certain cross-compiled environments due to defects in the way that FindProtobuf works in those cases.
> Add explicit option to disable protobuf tests

- LeapSerial/field_descriptor.h
- LeapSerial/serial_traits.h
- src/leapserial/test/MapTest.cpp
- src/leapserial/test/SerializationTest.cpp
We should probably allow pattern matching in all `primitive_serial_traits` types and simply change the inheritance to indicate whether the matched type is valid or not.  We only throw a hard error if a user attempts to instantiate one of the static methods in the type, which would imply an attempt to use rather than a simple query on the availability of a serializer.
> Provide more useful static assertions when performing descriptor instantiation

- LeapSerial/field_descriptor.h
Turns out that sometimes a serialization descriptor can contain fields from a base type, which means it's possible for a `field_descriptor` to be instantiated on a non-serializable type.  Eliminate the static assertion so we can still compile.
> Eliminate incorrect static assert

- LeapSerial/descriptors.h
- LeapSerial/field_serializer_t.h
- src/leapserial/descriptors.cpp
Need to do this because it's not always safe to actually perform descriptor initialization at init/load time, particularly on Windows where the loader lock may be held.
> Populate reflection with function pointers rather than raw descriptors

- LeapSerial/serial_traits.h
Silence some annoying warnings on Mac
> Add missing override keyword where appropriate

- src/leapserial/Archive.cpp
Attempting to read past the end of the stream is not an error, and should not swallow the number of bytes read.  Only return an error value if an error condition has actually been encountered.
> Fix stream read behavior

- LeapSerial/AESStream.h
- contrib/CMakeLists.txt
- contrib/aes/CMakeLists.txt
- contrib/aes/aes256.c
- contrib/aes/aes256.h
- src/leapserial/AESStream.cpp
- src/leapserial/CMakeLists.txt
- src/leapserial/test/AESStreamTest.cpp
- src/leapserial/test/CMakeLists.txt
This adds support for AES encryption in CFB mode.  This is a standardized algorithm suitable for use in any high security application requiring strong symmetric key encryption.
Encryption can be accomplished as so:
```C++
static const std::array<uint8_t, 32> sc_key{ 0x99, 0x84, 0x49, 0x28 };
std::vector<uint8_t> vec(45, 0);
std::stringstream ss;
leap::OutputStreamAdapter osa(ss);
leap::AESEncryptionStream cs(osa, sc_key);
cs.Write(vec.data(), vec.size());
```
Keys for an AES cipher must be exactly 32 bytes long.  Use PBKDF2 to generate a key of the required length from a passphrase.
> Add support for encryption

- LeapSerial/Archive.h
- LeapSerial/IInputStream.h
- LeapSerial/StreamAdapter.h
- src/leapserial/Archive.cpp
- src/leapserial/CMakeLists.txt
- src/leapserial/StreamAdapter.cpp
Other input stream types are isolated to their own headers, this one should be as well.
> Move input stream adapter to its own header

- src/leapserial/IArchiveImpl.cpp
Caused by not actually verifying that we read the number of bytes we requested that we read.
> Fix premature EOF check behavior

- LeapSerial/AESStream.h
- LeapSerial/CompressionStream.h
- LeapSerial/FilterStreamBase.h
- LeapSerial/LeapSerial.h
- src/leapserial/AESStream.cpp
- src/leapserial/CompressionStream.cpp
- src/leapserial/FilterStreamBase.cpp
- src/leapserial/test/AESStreamTest.cpp
- src/leapserial/test/CompressionStreamTest.cpp
This is necessary to allow a single stream to completely wrap the interior stream.  Otherwise, we wind up with memory management issues everywhere.  Furthermore, there should really be a concept of exclusive ownership, here--if someone attempted to directly access the underlying stream, we could possibly wind up with a state inconsistency that would be tough to resolve in the general case.
> Adapter streams should take ownership of their underlying fields

- LeapSerial/BoundedStream.h
- src/leapserial/BoundedStream.cpp
- src/leapserial/CMakeLists.txt
- src/leapserial/test/BoundedStreamTest.cpp
- src/leapserial/test/CMakeLists.txt
These are required to properly handle subsections of input streams
> Add bounded stream concepts

- src/leapserial/test/SerializationTest.cpp
Ensure that users can add identified members as they see fit to classes that may already have fixed-size structure concepts
> Add forwards and backwards compatibility tests

- LeapSerial/BufferedStream.h
- src/leapserial/BufferedStream.cpp
- src/leapserial/test/BufferedStreamTest.cpp
It's helpful to be able to specify, on creation, the number of bytes from the input buffer which should be treated as valid and ready-to-read.  Modify the buffered stream constructor to support this use pattern and extend tests to verify it works as we expect.
> Add buffered stream "initially valid" feature

- LeapSerial/BufferedStream.h
- LeapSerial/FilterStreamBase.h
- LeapSerial/MemoryStream.h
- src/leapserial/BufferedStream.cpp
- src/leapserial/FilterStreamBase.cpp
- src/leapserial/MemoryStream.cpp
- src/leapserial/test/AESStreamTest.cpp
- src/leapserial/test/BufferedStreamTest.cpp
- src/leapserial/test/CompressionStreamTest.cpp
Some streams are throwing exceptions when the EOF is reached, others set the EOF bit exactly when the last byte is read from the stream, and others still set the EOF bit when an attempt is made to read beyond the end of the file.
Standardize on the behavior defined by the STL:  The EOF bit indicates whether the last read operation read past the end of the file.  This bit gets set even if the last read operation successfully moved some data.
> Fix inconsistent stream EOF behaviors

- src/leapserial/StreamAdapter.cpp
Skip for the `InputStreamAdapter` type uses a very slow call to `ignore`; this can be made significantly faster if we just use a seek call directly.
> Enhance speed of `Skip` function

- LeapSerial/AESStream.h
- contrib/aes/CMakeLists.txt
- contrib/aes/rijndael-alg-fst.c
- contrib/aes/rijndael-alg-fst.h
- src/CMakeLists.txt
- src/leapserial/AESStream.cpp
- src/leapserial/test/AESStreamTest.cpp
- src/leapserialbench/Benchmark.h
- src/leapserialbench/CMakeLists.txt
- src/leapserialbench/Encryption.cpp
- src/leapserialbench/Encryption.h
- src/leapserialbench/LeapSerialBench.cpp
- src/leapserialbench/LeapSerialBench.h
- src/leapserialbench/Utility.cpp
- src/leapserialbench/Utility.h
- src/leapserialbench/stdafx.cpp
- src/leapserialbench/stdafx.h
Reports of slow performance in the AES encryption stream cipher have made it necessary to add a project to benchmark its performance and ensure that it approaches the performance that could be achieved with a plaintext read.  IO should be the limiting factor with a block encryption system such as AES, not compute.
> Add benchmark project

- CMakeLists.txt
This bug was discovered when building LeapIE on arm-linux.
> use -fPIC when building in ARM + C

- contrib/zlib/inflate.c
Turns out the only thing that was really needed here were better parenthesis.
> Second attempt to fix signed/unsigned problem

- src/leapserial/Archive.cpp
- src/leapserial/Archive.h
- src/leapserial/ArchiveFlatbuffer.cpp
- src/leapserial/ArchiveFlatbuffer.h
- src/leapserial/ArchiveJSON.cpp
- src/leapserial/ArchiveJSON.h
- src/leapserial/IArchiveImpl.h
- src/leapserial/IArchiveProtobuf.cpp
- src/leapserial/IArchiveProtobuf.h
- src/leapserial/OArchiveImpl.h
- src/leapserial/OArchiveProtobuf.cpp
- src/leapserial/OArchiveProtobuf.h
- src/leapserial/ProtobufType.h
- src/leapserial/ProtobufUtil.cpp
- src/leapserial/serial_traits.h
- src/leapserial/test/SerializationTest.cpp
Need to ensure that all write serializers support this type.
> Add support for `long double`

- CMakeLists.txt
Very minor change, lets us see the current compiler version number even if the version number check fails.
> Put compiler version status message earlier

- src/leapserial/test/SerializationTest.cpp
Unfortunately this isn't supported on Android, so we have to use the name from the global namespace rather than from `std`.
> Eliminate use of `std::nextafter`

- cmake-modules/FindProtobuf.cmake
- src/LeapSerial/test/CMakeLists.txt
When protobuf isn't found, we actually don't want to generate any kind of reference to it.
> Fix protobuf absence bug

- src/LeapSerial/CMakeLists.txt
Even though it's a header it must be explicitly named, otherwise it won't get packaged during the install step.
> Add missing source file

- src/LeapSerial/ArchiveLeapSerialV0.cpp
- src/LeapSerial/ArchiveLeapSerialV0.h
These names are inconsistent with respect to each other, clean them up.
> Make legacy archive names consistent

- version.cmake
There have been breaking changes in the LeapSerial interface and includes, need to update the version number accordingly.
> Bump LeapSerial version number

- src/LeapSerial/test/CMakeLists.txt
- src/LeapSerial/test/PathologicalTest.cpp
Looks like this test got forgotten about when the project was refactored, put it back in CMakeLists.txt and make it compile.
> Restore PathologicalTest

- src/LeapSerial/test/SerialCallbackTest.cpp
- src/LeapSerial/test/SerializationTest.cpp
Less code, clearer test.  Use a single `std::stringstream` in preference to a pair of separate `std::istringstream` and `std::ostringstream` instances.
> Use a single stream for a test

- src/LeapSerial/descriptors.cpp
MSVC2013 before the CTP doesn't have magic statics, so we need to make sure all of our descriptors are initialized on that platform in advance.
> Fix initialization race in MSVC2013

- src/LeapSerial/ArchiveLeapSerial.cpp
- src/LeapSerial/test/PathologicalTest.cpp
Looks like LeapSerial's base format isn't serializing and deserializing `bool` the same way.  Add a test to ensure we don't goof this up again, and then fix the issue.
> Minimal repro case for a bool issue

- src/LeapSerial/CompressionStream.cpp
- src/LeapSerial/FilterStreamBase.h
- src/LeapSerial/test/CompressionStreamTest.cpp
There are some defects that are only obvious when the compression stream is very large.  Make the unit tests verify the correct behavior of the compression stream when the input is very large, and fix any bugs that are uncovered.
> Make compressions stream test a bit more pathological

- src/LeapSerial/CompressionStream.cpp
- src/LeapSerial/CompressionStream.h
- src/LeapSerial/FilterStreamBase.cpp
- src/LeapSerial/test/CompressionStreamTest.cpp
Compression streams were fix to use the Zlib compression. This PR adds the ability to more easily support other compression schemes. It also fixes a couple of bugs.
IMPORTANT: This does include a breaking interface changes as well. The `leap::CompressionStream` and `leap::DecompressionStream` classes are now templated, specifying the compression type.
> Refactor compression stream

- src/LeapSerial/test/SerializationTest.cpp
This feature has been present in LeapSerial for awhile, but doesn't have any tests.  Add one.
> Add unit test for responsible deserialization

- src/LeapSerial/MemoryStream.h
One `MemoryStream` use case requires direct access to the serialized data once serialization is complete.  Provide accessor methods to do this.
> Add accessor methods to MemoryStream

- src/LeapSerial/ArchiveJSON.cpp
- src/LeapSerial/test/ArchiveJSONTest.cpp
`ArchiveJSON` doesn't support strings yet.  Add support and a test.
> Add a String implementation to `ArchiveJSON`

- cmake-modules/FindProtobuf.cmake
- src/LeapSerial/SchemaWriterProtobuf.h
- src/LeapSerial/test/ArchiveProtobufTest.cpp
- src/LeapSerial/test/CMakeLists.txt
- src/LeapSerial/test/SchemaTest.cpp
The protobuf build for LeapSerial isn't working any more.  Fix it so we can run the tests.  Also suppress warnings where possible--we can't fix the generated code and the warnings make it harder to see real issues.
While we're at it, also fix SchemaWriterProtobuf2's access protections, and simplify the protobuf tests where possible.
> Fix protobuf compatibility and support

- src/LeapSerial/SchemaWriterProtobuf.cpp
- src/LeapSerial/test/TestProtobuf.proto
This warning probably started once we updated to protobuf-3.0.0.
Since we're defaulting to `syntax = "proto2"`, and LeapSerial was developed on such, explicitly specify it. This removes the runtime warning:
```
Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
```
> Explicitly specify syntax = "proto2"

- src/LeapSerial/CMakeLists.txt
- src/LeapSerial/CompressionStream.cpp
- src/LeapSerial/CompressionStream.h
- src/LeapSerial/CompressionStreamInternal.h
- src/LeapSerial/test/CompressionStreamTest.cpp
This PR adds support for BZip2 compression when interacting with LeapSerial streams.
> Add BZip2 as a supported compression type

- standard/CombinedInstaller.cmake
- standard/StandardProject.cmake
CMAKE_OSX_ARCHITECTURES is actually assigned on the command line, and if not there, is assigned by CMake to an empty string. This means that it has a value when the set command is encountered, and therefore unless FORCE is also specified, the set will be ignored.
See leapmotion/leapserial#3 for more information.
Resubmission of #115
> CMAKE_OSX_ARCHITECTURES must be set with FORCE

- .travis.yml
- src/LeapSerial/test/CMakeLists.txt
> Fix Protobuf_NotFound Error in ExternalBuild

- .travis.yml
- CMakeLists.txt
With CMake 3.9 approaching, update our minimum requirement again.
Likewise doing this for autowiring and related repositories.
> Update minimum CMake requirement

- src/LeapSerial/ArchiveLeapSerial.cpp
The `data()` function was returning a pointer to the memory inside of the destroyed temporary object (`std::array<uint8_t, 10>`) returned by `ToBase128()`. Instead, make sure that the temporary outlives the use of the pointer.
> Prevent accessing memory of destroyed temporary object

- CMakeLists.txt
Visual Studio 2017 version 15.5 has deprecated the std::tr1 namespace. We've preferred using C++11 <tuple> on all platforms anyhow.
> Remove reference to std::tr1
